name: Salesforce Metadata Deploy

inputs:
  SFDX_AUTH_URL:
    description: 'Salesforce authentication URL'
    required: true
  SOURCE_DIRECTORY:
    description: 'Directory containing the source code'
    required: true
  WAIT:
    description: 'Wait time for the deployment'
    required: true
  TEST_LEVEL:
    description: 'Level of tests to run during deployment'
    required: true
    default: 'RunLocalTests'
  DRY_RUN:
    description: 'Perform a dry run of the deployment'
    required: false

runs:
  using: "composite"
  steps:
    - name: Install Salesforce CLI
      shell: bash
      run: |
        npm install -g @salesforce/cli
        sf --version
    - name: Login to Environment
      shell: bash
      run: |
        sf org login sfdx-url --set-default --sfdx-url-file <(echo "${{ inputs.SFDX_AUTH_URL }}")
    - name: Generate package.xml
      shell: bash
      run: |
        mkdir changed-sources        
        sf sgd:source:delta --from "HEAD~1" --output-dir changed-sources/ --generate-delta --source-dir ${{ inputs.SOURCE_DIRECTORY }}
    - name: Deploy to Environment
      shell: bash
      run: |
        deployFlags=(
          --manifest changed-sources/package/package.xml
          --post-destructive-changes changed-sources/destructiveChanges/destructiveChanges.xml
          --wait ${{ inputs.WAIT }}
          --test-level ${{ inputs.TEST_LEVEL }}
          --verbose
        )
        if [ "${{ inputs.DRY_RUN }}" = "true" ]; then
          deployFlags+=( --dry-run )
        
        sf project deploy start "${deployFlags[@]}"