name: "Validate Salesforce Changes"
description: "Validate Changes From Pull Request"
inputs:
  sfdx_auth_url:
    description: "The auth url tied to your deployment environment"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install Salesforce CLI
      run: |
        npm install @salesforce/cli --global
        sf --version
      shell: bash

    - name: Installing sfdx git delta
      run: |
        mkdir changed-sources
        sf sgd:source:delta --from "HEAD~1" --output-dir changed-sources/ --generate-delta --source-dir force-app/
      shell: bash

    - name: Authenticate to Org
      run: sf org login sfdx-url --set-default --sfdx-url-file <(echo "${{ inputs.SFDX_AUTH_URL }}")
      shell: bash

    - name: "Create delta packages for new, modified or deleted metadata"
      run: |
        mkdir changed-sources
        sf sgd:source:delta --from "HEAD~1" --output-dir changed-sources/ --generate-delta --source-dir force-app/
      shell: bash

    - name: "Upload changed-sources folder as artifact"
      uses: actions/upload-artifact@v4
      with:
        name: changed-sources
        path: changed-sources
      shell: bash

    - name: "Validate Changes"
      run: |
        deployFlags=(
          --manifest changed-sources/package/package.xml
          --post-destructive-changes changed-sources/destructiveChanges/destructiveChanges.xml
          --verbose
        )
        sf project validate start "${deployFlags[@]}"
      shell: bash