name: Close Production Pull Request

# only trigger on pull request closed events
on:
  pull_request:
    types: [closed]
    branches:
      - master
      - main
    paths:
      - 'force-app/**'
jobs:
  merge-job:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy on ${{ vars.ENVIRONMENT_NAME }}
        uses: ./.github/actions/metadata-test-deploy
        with:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
          DRY_RUN: false
          TEST_LEVEL: 'RunLocalTests'
  close-job:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo PR #${{ github.event.number }} has been closed without being merged