name: Deploy to SIT

on:
  pull_request:
    types: [closed]
    branches:
      - sit
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: sit
    steps:
      - uses: actions/checkout@v4
      - name: Validate on ${{ vars.ENVIRONMENT_NAME }}
        uses: ./.github/actions/validate-and-deploy
        with:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
          DRY_RUN: true
          TEST_LEVEL: RunLocalTests
