name: SFDX-CLI DEV Validate from Repository
on:
  push:
    branches:
      - develop
    paths:
      - 'force-app/**'
jobs:
  SFDX-CLI-DEV-Validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          # Fetch all history commit
          fetch-depth: 0
      - run: npm install -g @salesforce/cli
          sf --version
      - run: echo y | sfdx plugins:install sfdx-git-delta
          sfdx plugins
      - run: sf org login sfdx-url --set-default --sfdx-url-file <(echo "${{ secrets.SFDX_AUTH_URL }}")
      - run: git fetch origin "+refs/heads/*:refs/remotes/origin/*"
      - run: sfdx sgd:source:delta --to "HEAD" --from $(git merge-base HEAD origin/dev) --output . -i .gitignore
      - run: sfdx force:source:deploy -x package/package.xml -c -l RunLocalTests -u org