name: Validate Production Pull Request

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Validate Changes
        uses: ./.github/actions/validateDeployment
        with:
          sfdx_auth_url: ${{ secrets.SFDX_AUTH_URL }} }
