name: Validate Production Pull Request

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  validate:
    uses: ./.github/workflows/salesforce-metadata-deploy.yml
    with:
      environment-name: production
      dry-run: true
      test-level: RunAllTestsInOrg