name: Deploy To Production

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - master

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Set up Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: "Install Salesforce CLI"
        run: |
          npm install @salesforce/cli --global

      - name: "Installing sfdx git delta"
        run: |
          echo y | sf plugins install sfdx-git-delta
          sf plugins

      - name: "Authenticate to Org"
        run: |
          sf org login sfdx-url --set-default --sfdx-url-file <(echo "${{ secrets.SFDX_AUTH_URL }}")

      - name: "Create delta packages for new, modified or deleted metadata"
        run: |
          mkdir changed-sources
          sf sgd:source:delta --from "HEAD~1" --output-dir changed-sources/ --generate-delta --source-dir force-app/

      - name: "Deploy"
        run: |
          deployFlags=(
              --manifest changed-sources/package/package.xml
              --post-destructive-changes changed-sources/destructiveChanges/destructiveChanges.xml
              --test-level RunLocalTests
              --verbose
            )
          sf project deploy start "${deployFlags[@]}"
