name: Salesforce Metadata Deploy

on:
  workflow_call:
    inputs:
      DRY_RUN:
        description: "Validate deploy and run Apex tests but don't save to the org."
        type: boolean
      WAIT:
        description: "Number of minutes to wait for command to complete and display results."
        type: number
        default: 30
      TEST_LEVEL:
        description: "Deployment Apex testing level."
        type: string
        default: RunLocalTests

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Salesforce CLI
        run: |
          npm install @salesforce/cli --global

      - name: Installing sfdx git delta
        run: |
          echo y | sf plugins install sfdx-git-delta
          sf plugins

      - name: Authenticate to Org
        run: sf org login sfdx-url --set-default --sfdx-url-file <(echo "${{ secrets.SFDX_AUTH_URL }}")

      - name: Create delta packages for new, modified or deleted metadata
        run: |
          mkdir changed-sources
          sf sgd:source:delta --from "HEAD~1" --output-dir changed-sources/ --generate-delta --source-dir force-app/

      - name: Upload changed-sources folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: changed-sources
          path: changed-sources

      - name: Deploy to Environment
        run: |
          deployFlags=(
            --manifest changed-sources/package/package.xml
            --post-destructive-changes changed-sources/destructiveChanges/destructiveChanges.xml
            --wait ${{ inputs.WAIT }}
            --test-level ${{ inputs.TEST_LEVEL }}
            --verbose
            )
          if [ "${{ inputs.DRY_RUN }}" = "true" ]; then
             deployFlags+=( --dry-run )
          sf project deploy start "${deployFlags[@]}"
