name: Validate SIT

on:
  pull_request:
    branches:
      - sit
jobs:
  validate:
    runs-on: ubuntu-latest
    environment: sit
    steps:
      - uses: actions/checkout@v4
      - name: Validate on ${{ vars.ENVIRONMENT_NAME }}
        uses: ./.github/actions/validate-and-deploy
        with:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
          DRY_RUN: true