name: Validate Production Pull Request

on:
  push:
    branches:
      - master
    paths:
      - 'force-app/**'
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 1
      - name: Install Salesforce CLI
        shell: bash
        run: |
          npm install -g @salesforce/cli
          sf --version
      - name: 'Installing sfdx git delta'
        run: | 
          echo y | sfdx plugins:install sfdx-git-delta
          sfdx plugins
      - name: 'Login to Environment'
        shell: bash
        run: |
          sf org login sfdx-url --set-default --sfdx-url-file <(echo "${{ secrets.SFDX_AUTH_URL }}")
      - name: 'Generate package.xml'
        run: |
          sfdx sgd:source:delta --to "HEAD" --from $(git merge-base HEAD origin/dev) --output . -i .gitignore
      - name: Deploy to Environment
        shell: bash
        run: |
          sf project deploy validate -x package/package.xml -l RunLocalTests
