name: Validate Production

on:
  pull_request:
    branches:
      - master
jobs:
  validate:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Run Salesforce Code Analyzer
        uses: forcedotcom/run-code-analyzer@v2.1.0
      - name: Validate on ${{ vars.ENVIRONMENT_NAME }}
        uses: ./.github/actions/validate-and-deploy
        with:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
          TEST_LEVEL: RunAllTestsInOrg
          DRY_RUN: true