name: Validate Production Pull Request

on:
  push:
    branches:
      - master
    paths:
      - 'force-app/**'
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Salesforce CLI
        shell: bash
        run: |
          npm install -g @salesforce/cli
          sf --version
      - name: 'Installing sfdx git delta'
        run: | 
          echo y | sfdx plugins:install sfdx-git-delta
          sfdx plugins
      - name: 'Login to Environment'
        shell: bash
        run: |
          sf org login sfdx-url --set-default --sfdx-url-file <(echo "${{ secrets.SFDX_AUTH_URL }}")
      - name: 'Create delta packages for new, modified or deleted metadata'
        run: |
          mkdir changed-sources
          sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output-dir | -o changed-sources/ --generate-delta --source-dir | -s force-app/
      - name: 'Generate package.xml'
        shell: bash
        run: |
          sf project generate manifest --source-dir changed-sources/force-app --output-dir manifest
      - name: Deploy to Environment
        shell: bash
        run: |
          deployFlags=(
              --manifest manifest/package.xml
              --wait 30
              --test-level RunLocalTests
              --verbose
              --dry-run
            )
        
          sf project deploy start "${deployFlags[@]}"