name: Validate Production Pull Request

on:
  push:
    branches:
      - master
    paths:
      - 'force-app/**'
jobs:
  validate:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - name: Install Salesforce CLI
        shell: bash
        run: |
          npm install -g @salesforce/cli
          sf --version
      - name: 'Installing sfdx git delta'
        run: | 
          echo y | sf plugins install sfdx-git-delta
          sf plugins
      - name: 'Login to Environment'
        shell: bash
        run: |
          sf org login sfdx-url --set-default --sfdx-url-file <(echo "${{ secrets.SFDX_AUTH_URL }}")
      - name: 'Retrieve GIT'
        run: |
         git fetch origin "+refs/heads/*:refs/remotes/origin/*"
      - name: 'Generate package.xml'
        run: |
          mkdir changed-sources
          sf sgd:source:delta --from "HEAD~1" --output-dir changed-sources/ --generate-delta --source-dir force-app/
      - name: Deploy to Environment
        shell: bash
        run: |
          sf project deploy validate -x changed-sources/package/package.xml -l RunLocalTests
